# Generated by Django 4.2.3 on 2023-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
