# Generated by Django 4.2.3 on 2024-07-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='block',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='room_no',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
