# Generated by Django 4.2.3 on 2024-07-27 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_orderplaced_block_orderplaced_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='home.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
